version: "2"
services:

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /Users/admin/workspace/myproject:/data/myproject
    ports:
      - "80:80"
    links:
      - php:php

  php:
    build: ./php
    restart: always
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - /Users/admin/workspace/myproject:/data/myproject

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /Users/admin/workspace/myproject/docker-env/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
 
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /Users/admin/workspace/myproject/docker-env/redis:/data
    command: redis-server --appendonly yes
